// <auto-generated />
using System;
using Buy_Ticket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buy_Ticket.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buy_Ticket.Data.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cultural and financial heart of the city",
                            Icon = "⭐",
                            Name = "District 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Domestic & International Terminals",
                            Icon = "✈️",
                            Name = "Tan Son Nhat Airport"
                        },
                        new
                        {
                            Id = 3,
                            Description = "District 3, Central Hub",
                            Icon = "🚆",
                            Name = "Saigon Railway Station"
                        },
                        new
                        {
                            Id = 4,
                            Description = "East City Terminal Connections",
                            Icon = "🚌",
                            Name = "Da Lat Bus Station"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Emerging District 2 Riverside",
                            Icon = "🏙️",
                            Name = "Thu Thiem New Area"
                        });
                });

            modelBuilder.Entity("Buy_Ticket.Data.Entities.TicketOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentRef")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("QrPayload")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TicketOrders");
                });

            modelBuilder.Entity("Buy_Ticket.Data.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("DateText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 22,
                            DateText = "April 4, 2026",
                            DepartureTime = "08:30 AM",
                            DestinationId = 4,
                            Price = 350000m
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 18,
                            DateText = "April 4, 2026",
                            DepartureTime = "01:45 PM",
                            DestinationId = 4,
                            Price = 350000m
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 12,
                            DateText = "April 4, 2026",
                            DepartureTime = "08:00 PM",
                            DestinationId = 4,
                            Price = 370000m
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 30,
                            DateText = "April 4, 2026",
                            DepartureTime = "09:00 AM",
                            DestinationId = 2,
                            Price = 150000m
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 26,
                            DateText = "April 4, 2026",
                            DepartureTime = "11:20 AM",
                            DestinationId = 3,
                            Price = 180000m
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 28,
                            DateText = "April 4, 2026",
                            DepartureTime = "07:40 AM",
                            DestinationId = 5,
                            Price = 120000m
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 40,
                            DateText = "April 4, 2026",
                            DepartureTime = "10:00 AM",
                            DestinationId = 1,
                            Price = 200000m
                        });
                });

            modelBuilder.Entity("Buy_Ticket.Data.Entities.Trip", b =>
                {
                    b.HasOne("Buy_Ticket.Data.Entities.Destination", "Destination")
                        .WithMany("Trips")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Buy_Ticket.Data.Entities.Destination", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
